### ISSUE TITLE
Doesnt work with PNPM

### ISSUE THREAD

**Issue by EugeneKallis** [hperrin/smui-example-sveltekit#17]
Is there plans to support PNPM? Seems to fail when compiling SMUI styles

`Error: Can't find stylesheet to import.
  ╷
3 │ @use '@material/theme/color-palette';
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\theme\_smui-theme.scss 3:1                                               @use
  node_modules\.pnpm\smui-theme@6.2.0\node_modules\smui-theme\_index.scss 1:1  root stylesheet
    at Object.wrapException (C:\Users\ponzi\dev\smui-example-sveltekit\node_modules\.pnpm\sass@1.55.0\node_modules\sass\sass.dart.js:1247:17)
    at _EvaluateVisitor1._evaluate0$_loadStylesheet$4$baseUrl$forImport (C:\Users\ponzi\dev\smui-example-sveltekit\node_modules\.pnpm\sass@1.55.0\node_modules\sass\sass.dart.js:81013:19)
    at _EvaluateVisitor1._evaluate0$_loadStylesheet$3$baseUrl (C:\Users\ponzi\dev\smui-example-sveltekit\node_modules\.pnpm\sass@1.55.0\node_modules\sass\sass.dart.js:81039:19)
    at _EvaluateVisitor__loadModule_closure4.call$0 (C:\Users\ponzi\dev\smui-example-sveltekit\node_modules\.pnpm\sass@1.55.0\node_modules\sass\sass.dart.js:82401:21)
    at _EvaluateVisitor1._evaluate0$_withStackFrame$1$3 (C:\Users\ponzi\dev\smui-example-sveltekit\node_modules\.pnpm\sass@1.55.0\node_modules\sass\sass.dart.js:82023:25)
    at _EvaluateVisitor1._evaluate0$_withStackFrame$3 (C:\Users\ponzi\dev\smui-example-sveltekit\node_modules\.pnpm\sass@1.55.0\node_modules\sass\sass.dart.js:82029:19)
    at _EvaluateVisitor1._evaluate0$_loadModule$7$baseUrl$configuration$namesInErrors (C:\Users\ponzi\dev\smui-example-sveltekit\node_modules\.pnpm\sass@1.55.0\node_modules\sass\sass.dart.js:80463:13)
    at _EvaluateVisitor1._evaluate0$_loadModule$5$configuration (C:\Users\ponzi\dev\smui-example-sveltekit\node_modules\.pnpm\sass@1.55.0\node_modules\sass\sass.dart.js:80466:19)
    at _EvaluateVisitor1.visitUseRule$1 (C:\Users\ponzi\dev\smui-example-sveltekit\node_modules\.pnpm\sass@1.55.0\node_modules\sass\sass.dart.js:81300:13)
    at UseRule0.accept$1$1 (C:\Users\ponzi\dev\smui-example-sveltekit\node_modules\.pnpm\sass@1.55.0\node_modules\sass\sass.dart.js:98372:22) {
  formatted: "Error: Can't find stylesheet to import.\n" +
    '  ╷\n' +
    "3 │ @use '@material/theme/color-palette';\r\n" +
    '  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '  ╵\n' +
    '  src\\theme\\_smui-theme.scss 3:1                                               @use\n' +
    '  node_modules\\.pnpm\\smui-theme@6.2.0\\node_modules\\smui-theme\\_index.scss 1:1  root stylesheet',`

**Comment by DGollings** [comment]
can confirm, same issue here with SvelteKit 1.0

**Comment by tuckergordon** [comment]
There's a work around [here](https://github.com/hperrin/svelte-material-ui/issues/348#issuecomment-1420396242) for anyone trying to get this working in the meantime
